try {
  console.log(x);
  console.log("wroking");
} catch (err) {
  console.log("Server is under maintainance");
}
